version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - vcontrol_network
    depends_on:
      - db
  db:
    image: "postgres:15.1-bullseye"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vcontrol_db
      POSTGRES_USER: vcontrol_db_user
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - vcontrol_network

networks:
  vcontrol_network:

volumes:
  db_data:
    driver: local