version: "3.9"
services:
  db:
    image: "postgres:15.1-bullseye"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vcontrol_db
      POSTGRES_USER: vcontrol_db_user
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - vcontrol_network

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    networks:
      - vcontrol_network
    depends_on:
      - db
      - redis
  
  redis:
    image: redis:7-alpine
    restart: on-failure
    command: redis-server --save 60 1 --loglevel warning --requirepass redis-local-password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  vcontrol_network:

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
